name: fluttnotes
description: "Flutter notes use data local"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  datalocal: ^1.0.4
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.0
  provider: 6.0.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
